const types = {
    LOAD_PICS_REQUEST: 'LOAD_PICS_REQUEST',
    LOAD_PICS_SUCCESS: 'LOAD_PICS_SUCCESS',
    LOAD_PICS_FAILURE: 'LOAD_PICS_FAILURE',
    APPEND_PICS_REQUEST: 'APPEND_PICS_REQUEST',
    APPEND_PICS_SUCCESS: 'APPEND_PICS_SUCCESS',
    APPEND_PICS_FAILURE: 'APPEND_PICS_FAILURE',
    SHOW_SPINNER: 'SHOW_SPINNER',
    HIDE_SPINNER: 'HIDE_SPINNER',
};

export default types;